/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mmdc;

public class App {
    public static void main(String[] args) {
        new Array().run();
        new LinkedList().run();
        new Stack().run();
        new Queue().run();
    }
}
